# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockOutDate', models.DateTimeField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddress', models.CharField(max_length=6, unique=True)),
                ('requiresSignOff', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardToken', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationStart', models.DateTimeField()),
                ('reservationEnd', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_machine', to='api.Machine')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('NONE', 'Not Signed Off'), ('SOLO', 'Can Use Without Supervision'), ('SUPERVISED', 'Can Use With Supervision'), ('DEPARTMENTHEAD', 'Can Use Without Supervision & Grant Sign Offs')], max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_member_machine', to='api.Machine')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='reservations',
            field=models.ManyToManyField(related_name='reservation', through='api.Reservation', to='api.Machine'),
        ),
        migrations.AddField(
            model_name='member',
            name='signOffs',
            field=models.ManyToManyField(related_name='signoff', through='api.SignOff', to='api.Machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shop'),
        ),
        migrations.AddField(
            model_name='lockout',
            name='lockOutPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
        migrations.AddField(
            model_name='lockout',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Machine'),
        ),
    ]
