# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160804_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockout',
            name='lockOutEndDate',
        ),
    ]
