# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lockout_lockoutenddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', through='api.Reservation', to='api.Machine'),
        ),
    ]
