PROFILE = 'profile'
SELF = 'self'

_root = 'http://localhost:8000/api/v1/'
MEMBER_RESERVATION = _root + 'member-reservation'
MEMBER_SIGNOFFS = _root + 'member-signoffs'
MACHINE_RESERVATION = _root + 'machine-reservation'
MACHINE_SIGNOFFS = _root + 'machine-signoffs'
USER_GROUPS = _root + 'user-groups'
GROUP_USER = _root + 'group-users'
SIGNOFF_MEMBERS = _root + 'signoff-members'
SIGNOFF_MACHINES = _root + 'signoff-machines'
RESERVATION_MEMBERS = _root + 'reservation-members'
RESERVATION_MACHINES = _root + 'reservation-machines'
